Backported some of the updates to the old sysinit files for DEB and RPM.

diff --git a/repose-aggregator/artifacts/src/config/scripts/repose-valve-deb b/repose-aggregator/artifacts/src/config/scripts/repose-valve-deb
--- a/repose-aggregator/artifacts/src/config/scripts/repose-valve-deb
+++ b/repose-aggregator/artifacts/src/config/scripts/repose-valve-deb
@@ -33,18 +33,24 @@ CLEAN=/usr/bin/clean-repose-deploy
 # Can override the defaults in /etc/sysconfig
 . /etc/sysconfig/repose
 
-# First validate that we have a java executable on the path
-command -v $JAVA >/dev/null 2>&1 || { echo 'Repose requires the $JAVA environment variable be set to a Java executable! This can be done in the sourced /etc/sysconfig/repose file. Exiting!'; exit 1; }
+# Validate that we have a java executable on the path
+command -v $JAVA >/dev/null 2>&1
+if [ $? -gt 0 ]; then
+  echo 'Repose requires the "JAVA" environment variable be set to the absolute path of a Java executable!'
+  echo " - The current value ($JAVA) is invalid."
+  echo ' - This can be updated in the configuration file: /etc/sysconfig/repose'
+  echo 'Exiting!'
+  exit 1
+fi
 
-# We've found a java on the path, now validate that the minor is at least 7
-# testing to figure out java version stuff
-# We're not guaranteed to have bash on debians, so we have to use sh stuff
+# We've found a java on the path, now validate that the minor version is adequate.
+# We're not guaranteed to have bash on Debian flavors, so we have to use sh stuff.
 VERSION=$($JAVA -version 2>&1 | grep ' version' | awk '{ print substr($3, 2, length($3)-2); }')
 JAVA_MINOR=$(echo $VERSION | tr "." " " | cut -d " " -f2)
 
 if [ "$JAVA_MINOR" -lt "8" ]; then
-  echo "Repose requires a Java version of at least 8 to function."
-  echo "Please install a JRE 1.8 or greater."
+  echo 'Repose requires a Java version of at least 8 to function.'
+  echo 'Please install a JRE 1.8 or greater.'
   exit 1
 fi
 
